# English

# Statuses
murderhour.statuses.exhausted_1.title=Exhausted
murderhour.statuses.left_leg_broken_1.title=Left Leg Casted
murderhour.statuses.left_leg_broken_2.title=Left Leg Broken
murderhour.statuses.right_leg_broken_1.title=Right Leg Casted
murderhour.statuses.right_leg_broken_2.title=Right Leg Broken
murderhour.statuses.drunk_1.title=Tipsy
murderhour.statuses.drunk_2.title=Drunk
murderhour.statuses.drunk_3.title=Wasted
murderhour.statuses.drunk_4.title=Blackout Drunk
murderhour.statuses.drunk_5.title=Alchohol Poisoned
murderhour.statuses.blackout_1.title=Toppled Over
murderhour.statuses.blackout_2.title=Knocked Out
murderhour.statuses.blackout_3.title=Dying

murderhour.statuses.hidden_1.title=Hidden

murderhour.statuses.bruise_1.title=Lightly Bruised
murderhour.statuses.bruise_2.title=Bruised
murderhour.statuses.bruise_3.title=Heavily Bruised
murderhour.statuses.bruise_4.title=Majorly Bruised
murderhour.statuses.bruise_5.title=Extremely Bruised

# Bleed Effects
murderhour.statuses.bleed_steady_1.title=Steady Bleed
murderhour.statuses.bleed_steady_2.title=Heavy Steady Bleed
murderhour.statuses.bleed_steady_3.title=Fountain Bleed

murderhour.statuses.bleed_spurt_1.title=Spurting Bleed
murderhour.statuses.bleed_spurt_2.title=Gushing Bleed
murderhour.statuses.bleed_spurt_3.title=Fatal Gushing Bleed


# Interactions
murderhour.interact=Select Interaction
murderhour.interaction.pickup=Pickup
murderhour.interaction.open=Open
murderhour.interaction.lockpick=Attempt Lockpick
murderhour.interaction.lock=Lock
murderhour.interaction.claim=Claim

# Actions
murderhour.action.lockpick=Attempting to lockpick...

murderhour.action.assesscondition=Assessing condition...
murderhour.action.beingassessed=Being assessed...